force-app/main/default/objects/Event_Plan__c/Event_Plan__c.object-meta.xml
<CustomObject>
    <description>Represents individual events planned by Tech Mahindra</description>
    <label>Event Plan</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Event Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Plan__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>The date and time of the event.</description>
    <label>Event Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Plan__c/fields/Event_Flag__c.field-meta.xml
<CustomField>
    <fullName>Event_Flag__c</fullName>
    <defaultValue>&apos;On Track&apos;</defaultValue>
    <description>The internal indicator to monitor and manage the overall health status of the event</description>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Track</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Plan__c/fields/Pending_Tasks_Count__c.field-meta.xml
<CustomField>
    <fullName>Pending_Tasks_Count__c</fullName>
    <description>The Roll-Up Summary field automatically calculates and stores the total count of pending 
tasks associated with each event.</description>
    <label>Pending Tasks Count</label>
    <summaryFilterItems>
        <field>Event_Task__c.Task_Status__c</field>
        <operation>equals</operation>
        <value>Not Started, In Progress</value>
    </summaryFilterItems>
    <summaryForeignKey>Event_Task__c.Event_Plan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Event_Plan__c/fields/Total_Tasks_Count__c.field-meta.xml
<CustomField>
    <fullName>Total_Tasks_Count__c</fullName>
    <description>The Roll-Up Summary field automatically calculates and stores the total count of tasks associated with each event.</description>
    <label>Total Tasks Count</label>
    <summaryForeignKey>Event_Task__c.Event_Plan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Event_Task__c/Event_Task__c.object-meta.xml
<CustomObject>
    <description>Represents tasks associated with event planning.</description>
    <label>Event Task</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>Event Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Task__c/fields/Event_Plan__c.field-meta.xml
<CustomField>
    <fullName>Event_Plan__c</fullName>
    <description>The event plan associated with the event task.</description>
    <label>Event Plan</label>
    <referenceTo>Event_Plan__c</referenceTo>
    <relationshipLabel>Event Tasks</relationshipLabel>
    <relationshipName>Event_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Task__c/fields/Task_Status__c.field-meta.xml
<CustomField>
    <fullName>Task_Status__c</fullName>
    <defaultValue>&apos;Not Started&apos;</defaultValue>
    <description>The current status of the task.</description>
    <label>Task Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventTaskHealthCheckTriggerHandler.cls
public class EventTaskHealthCheckTriggerHandler {
   public void handlerAfterInsert(List<Event_Task__c> newEventTasks) {
   updateEventFlags(newEventTasks);
   }
   public void handlerAfterUpdate(List<Event_Task__c> newEventTasks, Map<Id, Event_Task__c> 
   oldEventTasks) {
   updateEventFlags(newEventTasks);
   }
   public void handlerAfterDelete(List<Event_Task__c> deletedEventTasks) {
   updateEventFlags(deletedEventTasks);
   }
   //Common method to update the flag used by all the methods
   private void updateEventFlags(List<Event_Task__c> eventTasks) {
     system.debug(eventTasks);
       //saving event plan ids associated with event Tasks
     set<Id> evPlanId=new set<Id>();
     for(Event_Task__c task : eventTasks ){
         if(task.Event_Plan__c !=null){
             evPlanId.add(task.Event_Plan__c);
         }
     }
     
     if(evPlanId.isEmpty())
         return;//program will stop here
     
     list<Event_Plan__c> evplans=new list<Event_Plan__c>();
     //SOQL to get event plan  object data
     evplans=[select id,Total_Tasks_Count__c,Pending_Tasks_Count__c ,Event_Date__c,Event_Flag__c from Event_Plan__c where id=:evPlanId AND Event_Date__c >= TODAY AND Event_Date__c <= NEXT_N_DAYS:7];
     system.debug(evplans);
     //Since it was showing old data and not showing the updated data so i am using aggregate functions to get the updated values
     //getting the updated pending task count
     map<id,integer> ptc=new map<id,integer>();
     for(AggregateResult res: [select Event_Plan__c Id,count(id) taskCount from Event_Task__c where Event_Plan__c=:evPlanId and Task_Status__c!='Completed' group by Event_Plan__c]){
         ptc.put((id) res.get('Id'),(integer) res.get('taskCount'));
     }
     
     //getting the updated total task count
       map<id,integer> ttc=new map<id,integer>();
     for(AggregateResult res: [select Event_Plan__c Id,count(id) ttaskCount from Event_Task__c where Event_Plan__c=:evPlanId group by Event_Plan__c]){
         ttc.put((id) res.get('Id'),(integer) res.get('ttaskCount'));
     }
     
      //system.debug([select Event_Plan__c id,count(id) taskCount from Event_Task__c where Event_Plan__c=:evPlanId  group by Event_Plan__c]);
     for(Event_Plan__c ev: evplans){
         Integer pt=ptc.get(ev.Id)!=null?ptc.get(ev.Id):0;
         Integer tt=ttc.get(ev.Id)!=null?ttc.get(ev.Id):0;
        //total task count should be greater than 0
     if(tt>0){
         decimal c=(pt*100/tt);// calculating percentage to change the event status 
          system.debug(c);
          system.debug(pt+' '+tt);
         if(c>=50){
            ev.Event_Flag__c='Critical';
         }
         else if(c==0){
            ev.Event_Flag__c='Completed'; 
         }
         else{
            ev.Event_Flag__c='On Track';
         }
      } else{
            ev.Event_Flag__c='On Track';
            }
      }
      //DML Operation to update the records
      update evplans;
 }
}