force-app/main/default/objects/Event_Plan__c/Event_Plan__c.object-meta.xml
<CustomObject>
    <description>Represents individual events planned by Tech Mahindra</description>
    <label>Event Plan</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Event Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Task__c/Event_Task__c.object-meta.xml
<CustomObject>
    <description>Represents tasks associated with event planning.</description>
    <label>Event Task</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>Event Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>The deadline for completing the task</description>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event_Task__c/fields/Event_Plan__c.field-meta.xml
<CustomField>
    <fullName>Event_Plan__c</fullName>
    <description>The event plan associated with the event task.</description>
    <label>Event Plan</label>
    <referenceTo>Event_Plan__c</referenceTo>
    <relationshipLabel>Event Tasks</relationshipLabel>
    <relationshipName>Event_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Task__c/fields/Task_Status__c.field-meta.xml
<CustomField>
    <fullName>Task_Status__c</fullName>
    <defaultValue>&apos;Not Started&apos;</defaultValue>
    <description>The current status of the task.</description>
    <label>Task Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetOpenTasks.cls
public class GetOpenTasks {
    @InvocableMethod(label='Get Open Tasks' description='Returns open tasks ordered by due date descending')
    public static List<Event_Task__c> getOpenTasks(List<Id> eventPlanIds) {
        return [
            SELECT Id, Name, Task_Status__c, Due_Date__c
            FROM Event_Task__c
            WHERE Event_Plan__c =:eventPlanIds
            AND Task_Status__c = 'Not Started'
            ORDER BY Due_Date__c DESC
        ];
    }
}